name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Check Node.js version
      run: node -v

    - name: Clean and install backend dependencies
      run: |
        cd backend
        rm -rf node_modules
        npm install
        npm rebuild bcrypt

    - name: Run backend tests
      run: |
        cd backend
        npm test

    - name: Clean and install frontend dependencies
      run: |
        cd frontend
        rm -rf node_modules
        npm install

    - name: Run frontend tests
      run: |
        cd frontend
        npx vitest run

    - name: Clean and install Cypress dependencies
      run: |
        cd e2e-tests-cypress
        rm -rf node_modules
        npm install

    - name: Run Cypress tests
      run: |
        cd e2e-tests-cypress
        npx cypress run
      env:
        CYPRESS_baseUrl: http://localhost:5173
        NODE_ENV: test
